services:
  voiceisolatepro:
    image: voiceisolatepro
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
